# Generated by Django 3.0.4 on 2020-04-19 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
        migrations.AddField(
            model_name='ingreso',
            name='descripcion',
            field=models.CharField(max_length=200, null=True, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='monto',
            field=models.IntegerField(verbose_name='monto'),
        ),
    ]
