# Generated by Django 3.0.4 on 2020-04-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0003_auto_20200420_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha'),
        ),
    ]
