# Generated by Django 3.0.4 on 2020-04-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0004_movimiento_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
    ]
