# Generated by Django 3.0.4 on 2020-04-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0005_auto_20200420_0311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Cuenta',
        ),
    ]
