# Generated by Django 3.0.4 on 2020-04-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0007_auto_20200420_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='detalle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='detalle'),
        ),
    ]
